### ISSUE TITLE
Framerate not running at max speed.

### ISSUE THREAD

**Issue by silent-code** [apl-ocean-engineering/liboculus#20]
In oculus_client.cpp, using the config.setPingRate method, I'm setting the ping rate to pingRateHighest. 

However, I'm only achieving a max of around 15 Hz, not the desired 40 Hz. 

I'm using the 3Mhz mode with a range of 3m. 

Please advise. 
Thanks in advance! 
-Tim

**Comment by HikariS97** [comment]
The actual pingrate is relating to max operating range. The max pingrate you set can be considered as the maximum pingrate you can get, but not the actual pingrate.

**Comment by silent-code** [comment]
Thanks for the response. 

I understand your explanation between the requested and actual ping rates in the oculus_client.cpp application. However, in the Oculus ViewPoint software that comes with the Oculus sonar, it appears to run at the max 40hz rate in all range/frequency modes. 

I'm wondering if there's something in the oculus_client.cpp callback structure that is preventing the ping rate from achieving the max 40 hz rate? 

If anyone has encountered this issue please advise.

**Comment by amarburg** [comment]
I will admit that we haven't spent much time exercising the faster ping rates -- the default 10Hz has been sufficient for us.   For a while, it seemed to me that the ping rate selection was unreliable at best (e.g., it seemed like the relationship between the rate requested and the new sensor rate were non-deterministic, based on the rate you were coming *from* etc); though that was with a much older version of the Oculus firmware.

We'll have our 3MHz unit back in the tank in the next week, I can cross-check your results.

**Comment by silent-code** [comment]
Ok thank you and thanks for providing this flexible api!

**Comment by silent-code** [comment]
Actually, after poking around in the Oculus ViewPoint app settings display, there does not appear a way to verify the actual ping rate. So you all may be correct that 40hz is the requested rate but the actual ping rate is non-deterministic.

**Comment by amarburg** [comment]
I wanted to follow up on this.   So these results are all for my M3000d, running in HF mode, with 512 beams, and a range of 2.0m -- which results in 505 range bins.

All Hz are reported by observing the publication rate of the `sonar_image` rostopic from our full ROS stack -- I doubt ROS is a source of inefficiency here.

For 8 bit data:
Ping rate 0 (10Hz), rostopic rate 10 Hz
Ping rate 1 (15Hz), rostopic rate 10.5 Hz
Ping rate 2 (40Hz), rostopic rate 10.5 Hz
Ping rate 3 (5Hz), rostopic rate 5 Hz
Ping rate 4 (2Hz), rostopic rate 2 Hz
Ping rate 5 (standby), rostopic rate 0

For 16 bit data:
Ping rate 0, rostopic rate 8.5 Hz
Ping rate 1, rostopic rate 8.5 Hz
Ping rate 2, rostopic rate 8.5 Hz
Ping rate 3, rostopic rate 5.0 Hz
Ping rate 4, rostopic rate 2.0 Hz
Ping rate 5, rostopic rate 0

For 32 bit data:
Ping rate 0, rostopic rate 6.16 Hz
Ping rate 1, rostopic rate 6.16 Hz
Ping rate 2, rostopic rate 6.16 Hz
Ping rate 3, rostopic rate 5.0 Hz
Ping rate 4, rostopic rate 2.0 Hz
Ping rate 5, rostopic rate 0

For the 32 bit data, the system reports a packet size of 1038308 bytes.   At 6.16 Hz that's 51.2e6 bits per second, or about 48.8 Mbit (on a 100 Mbit connection).  So not maxing out the pipe but a lot of data.   That ratio does get worse for the smaller data sizes, though.

I'm open to the idea that it's due to inefficiency in the lib, but we are seeing sequential ping IDs, so I don't think we're dropping any data packets.
